### ISSUE TITLE
Fix running of npm install on volo create

### ISSUE THREAD

**Issue by arikon** [arikon/tpl-cli#3]
```
$ volo create bem-version arikon/tpl-cli
Downloading: https://codeload.github.com/arikon/tpl-cli/legacy.zip/v4
npm
 ERR! install Couldn't read dependencies
npm ERR!
 Error: Invalid name: "{app}"
npm
ERR!     at ensureValidName (/Users/arikon/n/versions/0.8.25/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:281:15)
npm
 ERR!     at Object.module.exports.fixNameField (/Users/arikon/n/versions/0.8.25/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:196:5)
npm
ERR!     at /Users/arikon/n/versions/0.8.25/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
npm ERR!
     at Array.forEach (native)
npm ERR!
     at normalize (/Users/arikon/n/versions/0.8.25/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
npm ERR!
     at final (/Users/arikon/n/versions/0.8.25/lib/node_modules/npm/node_modules/read-package-json/read-json.js:310:33)
npm ERR!
     at then (/Users/arikon/n/versions/0.8.25/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:33)
npm
ERR!     at /Users/arikon/n/versions/0.8.25/lib/node_modules/npm/node_modules/read-package-json/read-json.js:234:40
npm ERR!
     at fs.readFile (fs.js:176:14)
npm ERR!     at /Users/arikon/n/versions/0.8.25/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm
ERR! If you need help, you may report this log at:
npm
ERR!     <http://github.com/isaacs/npm/issues>
npm ERR!
 or email it to:
npm ERR!
     <npm-@googlegroups.com>

npm
 ERR! System Darwin 12.4.0
npm
ERR! command "node" "/Users/arikon/n/bin/npm" "install"
npm ERR! cwd /Users/arikon/projects/bem/bem-version
npm
ERR! node -v v0.8.25
npm ERR!
npm -v 1.3.4
npm
 ERR!

npm ERR!
 Additional logging details can be found in:
npm
 ERR!
     /Users/arikon/projects/bem/bem-version/npm-debug.log
npm
 ERR!
not ok code 0
Project directory is ready!

Do not forget to
- run `npm init` to initialize npm package
- run `git init` to create git repository
- review CONTRIBUTING.md
- commit your project
https://api.github.com/repos/arikon/tpl-cli/zipball/v4 used to create bem-version
```

**Comment by arikon** [comment]
Fixed in v7
